version: '3.8'

services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  orderprocessor.ui:
    build:
      context: .
      dockerfile: OrderProcessor.UI/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=${MYSQL_DATABASE};Uid=root;Pwd=${MYSQL_ROOT_PASSWORD};"
      IMAP_SERVER: ${IMAP_SERVER}
      IMAP_PORT: ${IMAP_PORT}
      IMAP_USERNAME: ${IMAP_USERNAME}
      IMAP_PASSWORD: ${IMAP_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_API_URL: http://ollama:11434/api/generate
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - ./eml_files:/app/eml_files
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_started

volumes:
  mysql_data: 
  ollama_data: 